name: meg_m2_rnaseq_bash
# novel environment created in 2024 (from template meg_m2_rnaseq_bash) for the novel RNAseq pipeline on mouse data (adapted from the CEA RNAseq course)

# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # Bash environment
  - python>=3.8
  - pip
  - pip:
    - bash_kernel
  # For the M2 course:
  - fastqc
  - fastp
  - fastq-screen
  - samtools
  - multiqc
  - qualimap
  - bedtools
  - htseq
